name: Build and deploy Node.js app to Azure Web App - CoinSparkV1

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      # Debug step to list files in the checked out repository
      - name: List files in the repository
        run: |
          dir
          
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd path/to/your/project # Change this to the actual path if package.json is not in the root
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: path/to/your/project # Change this to the actual path

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      # Debug step to list files after downloading the artifact
      - name: List files after downloading artifact
        run: |
          ls -la

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32D4015952834BEC8E0A092C8F886AC7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56A320C656504E7B8869DFA123FFB52E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_91DEB57631764204A845EABF9124BB6B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'CoinSparkV1'
          slot-name: 'Production'
          package: .
